### ISSUE TITLE
BUG: Generalize name in build.create_network

### ISSUE THREAD

**Issue by ydoJ** [engri-1101/vinal#3]
Changes in commit c01faf0e55e832f9b2723522b322e5297301d75a do not work for etching tsp problems (special case). 

For example,
`nodes = pd.read_csv('data/xqf131_etching.csv', index_col=0)`
`G = vl.create_network(nodes, directed=True, manhattan=False, x_i='x_start', y_i='y_start', x_j='x_end', y_j='y_end')`

The columns are 'x_start', 'y_start', 'x_end', and 'y_end', so the nodes do not have attributes 'x' and 'y' (see line 80).

**Comment by henryrobbins** [comment]
@ydoJ Thanks for creating the issue--I will try to resolve soon, hopefully tomorrow

**Comment by henryrobbins** [comment]
So much for tomorrow... Did you end up fixing this or is this still open? @ydoJ

**Comment by ydoJ** [comment]
This is still open. Labs are getting updated to use the latest version of vinal, so more people might encounter this issue.

**Comment by henryrobbins** [comment]
@6x9equals42 This issue deals with item 2(a) from your email. Will merge in a fix now.

**Comment by henryrobbins** [comment]
The etching use case of vinal in the [ENGRI 1101 textbook](https://github.com/engri-1101/textbook) is a specific use-case. engri-1101/textbook#6 resolves this issue.
